SELECT  DISTINCT
	
	P.PersonID,
	P.FullName,
	LAST_VALUE ( I.CustomerID) OVER (PARTITION BY P.PersonID 	ORDER BY P.PersonID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS [CustomerID],
	LAST_VALUE ( C.CustomerName) OVER (PARTITION BY P.PersonID 	ORDER BY P.PersonID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS [CustomerFullName],
	LAST_VALUE ( IL.UnitPrice) OVER (PARTITION BY P.PersonID 	ORDER BY P.PersonID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS [UnitPrice],
	LAST_VALUE ( I.InvoiceDate) OVER (PARTITION BY P.PersonID 	ORDER BY P.PersonID ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS [InvoiceDate]
FROM Application.People AS P
	 INNER JOIN Sales.Invoices AS I	 ON P.PersonID=I.SalespersonPersonID
	 INNER JOIN Sales.Customers AS C ON C.CustomerID=I.CustomerID
	 INNER JOIN Sales.InvoiceLines AS IL ON IL.InvoiceID = I.InvoiceID;
