  WITH CTE AS
  (
   SELECT *,COUNT(*) OVER (PARTITION BY (W.StockItemName) ORDER BY (W.StockItemName) RANGE UNBOUNDED PRECEDING) AS [COUNT_by NAME]
   FROM Warehouse.StockItems  AS W 
  )
 SELECT CTE.StockItemID,
	CTE.StockItemName,
	CTE.Brand,
	CTE.UnitPrice, 
	COUNT(*) OVER ( ORDER BY (CTE.StockItemID) RANGE UNBOUNDED PRECEDING) AS [COUNT_ALL],
		ROW_NUMBER()  OVER (ORDER BY CTE.StockItemID desc) AS [NUMBER], CTE.[COUNT_by NAME] FROM CTE
